services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
      DJ_HOST: db
      DJ_USER: dev
      DJ_PASS: devpass
    networks:
      - devcontainer
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./init-dev-privileges.sql:/docker-entrypoint-initdb.d/init-dev-privileges.sql:ro
    networks:
      - devcontainer

networks:
  devcontainer:
    driver: bridge
